// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqczjmelvjyjlueuytzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxY3pqbWVsdmp5amx1ZXV5dHpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjM2ODksImV4cCI6MjA2NzE5OTY4OX0.7E4AagPROWnP3j7jnEI3g1gampyLWSehYUyUJY2VloE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});